ktor:
    development: true
    application:
        modules:
            - io.ktor.chat.RootModuleKt.rootModule
            - io.ktor.chat.RestModuleKt.restModule
            - io.ktor.chat.HealthCheckKt.healthCheckModule
            - io.ktor.chat.DatabasesKt.databaseModule
            - io.ktor.chat.RepositoriesKt.repositoriesModule
            - io.ktor.chat.AuthenticationKt.authModule
            - io.ktor.chat.AdminKt.adminModule
    deployment:
        port: 8081

jwt:
    audience: audience
    issuer: issuer
    realm: realm

security:
    secret: S3crE4_P@55w0Rd

database:
    main:
        url: "jdbc:postgresql://host.docker.internal:5440/chat"
        user: username
        driver: org.postgresql.Driver
        password: password
    test:
        url: "jdbc:h2:file:../h2/db"
        user: root
        driver: org.h2.Driver
        password: ""
