# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - "5440:5432"
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      - 'POSTGRES_USER=username'
      - 'POSTGRES_DB=chat'
      - 'POSTGRES_PASSWORD=password'
#      POSTGRES_USER: "username"
#      POSTGRES_DB: "test"
#      POSTGRES_PASSWORD: "password"
  admin:
    image: ktor-docker-image:ktor-chat-admin
    ports:
      - "8081:8081"
  chat:
    image: ktor-docker-image:ktor-chat-rest
    ports:
      - "8080:8080"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8085:8080"
