ktor:
    development: true
    application:
        modules:
            - io.ktor.chat.RootKt.root
            - io.ktor.chat.LoggingKt.logging
            - io.ktor.chat.SecurityKt.security
            - io.ktor.chat.MailKt.mail
            - io.ktor.chat.RestKt.rest
            - io.ktor.chat.HealthCheckKt.healthCheck
            - io.ktor.chat.DatabasesKt.database
            - io.ktor.chat.RepositoriesKt.repositories
            - io.ktor.chat.AuthenticationKt.auth
            - io.ktor.chat.UsersKt.users
            - io.ktor.chat.MessagesKt.messages
            - io.ktor.chat.RoomsKt.rooms
            - io.ktor.chat.MembershipsKt.members
    deployment:
        port: 8080

jwt:
    audience: audience
    issuer: issuer
    realm: realm

security:
    secret: S3crE4_P@55w0Rd

database:
    main:
        url: "jdbc:postgresql://host.docker.internal:5440/chat"
        user: username
        driver: org.postgresql.Driver
        password: password
    test:
        url: "jdbc:h2:file:../h2/db"
        user: root
        driver: org.h2.Driver
        password: ""
